# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5 import QtCore
from PyQt5 import QtGui



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(871, 685)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.mainpage = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainpage.sizePolicy().hasHeightForWidth())
        self.mainpage.setSizePolicy(sizePolicy)
        self.mainpage.setAutoFillBackground(False)
        self.mainpage.setObjectName("mainpage")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.mainpage)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton = QtWidgets.QPushButton(self.mainpage)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pushButton_2 = QtWidgets.QPushButton(self.mainpage)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.graphicsView = QtWidgets.QGraphicsView(self.mainpage)
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout.addWidget(self.graphicsView)
        self.verticalLayout_2.addWidget(self.mainpage)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 871, 27))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionopen = QtWidgets.QAction(MainWindow)
        self.actionopen.setObjectName("actionopen")
        self.actionclose = QtWidgets.QAction(MainWindow)
        self.actionclose.setObjectName("actionclose")
        self.actionopen_Floder = QtWidgets.QAction(MainWindow)
        self.actionopen_Floder.setObjectName("actionopen_Floder")
        self.actionclose_2 = QtWidgets.QAction(MainWindow)
        self.actionclose_2.setObjectName("actionclose_2")
        self.menu.addSeparator()
        self.menu.addAction(self.actionopen)
        self.menu.addSeparator()
        self.menu.addAction(self.actionopen_Floder)
        self.menu.addSeparator()
        self.menu.addAction(self.actionclose_2)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        #my
        self.myUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "上一张"))
        self.pushButton_2.setText(_translate("MainWindow", "下一张"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.actionopen.setText(_translate("MainWindow", "open"))
        self.actionclose.setText(_translate("MainWindow", "close"))
        self.actionopen_Floder.setText(_translate("MainWindow", "open Floder"))
        self.actionclose_2.setText(_translate("MainWindow", "close"))
        
    def myUi(self, MainWindow):
        self.imgpage = QtWidgets.QLabel(self.mainpage)
        self.imgpage.setObjectName("imgView")
        self.verticalLayout.addWidget(self.imgpage)
        self.imgpage.setPixmap(QtGui.QPixmap("C:\\Users\\hp\\Desktop\\trian\\1.png"))
        
        self.fd = QtWidgets.QFileDialog(MainWindow, '文件选择', './', 'all(*.*);;images(*.png *.jpg);;python(*.py)')
        self.fd.setAcceptMode(QtWidgets.QFileDialog.AcceptOpen)
        
        self.actionopen_Floder.triggered.connect(self.fd.show)
        self.actionopen_Floder.triggered.connect(self.process)
        
        self.pushButton.clicked.connect(self.previous_img)
        self.pushButton_2.clicked.connect(self.graphicsView.update)
        
    def process(self, a):
        print(a)

    def previous_img(self,a):
        print(a)
        
    def next_img(self, a):
        print(a)