# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demo1.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(961, 728)
        MainWindow.setTabletTracking(False)
        MainWindow.setAcceptDrops(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon/2.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(170, 270, 640, 360))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_serial_state = QtWidgets.QLabel(self.centralwidget)
        self.label_serial_state.setGeometry(QtCore.QRect(10, 60, 271, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_serial_state.setFont(font)
        self.label_serial_state.setTextFormat(QtCore.Qt.AutoText)
        self.label_serial_state.setObjectName("label_serial_state")
        self.pushButtonClose = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonClose.setGeometry(QtCore.QRect(420, 660, 93, 28))
        self.pushButtonClose.setObjectName("pushButtonClose")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(130, 150, 711, 91))
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_slider = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_slider.sizePolicy().hasHeightForWidth())
        self.label_slider.setSizePolicy(sizePolicy)
        self.label_slider.setScaledContents(False)
        self.label_slider.setObjectName("label_slider")
        self.horizontalLayout_2.addWidget(self.label_slider)
        self.horizontalSlider = QtWidgets.QSlider(self.widget)
        self.horizontalSlider.setMouseTracking(False)
        self.horizontalSlider.setMaximum(360)
        self.horizontalSlider.setProperty("value", 0)
        self.horizontalSlider.setSliderPosition(0)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalLayout_2.addWidget(self.horizontalSlider)
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(110, 10, 741, 121))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButtonForeward = QtWidgets.QPushButton(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonForeward.sizePolicy().hasHeightForWidth())
        self.pushButtonForeward.setSizePolicy(sizePolicy)
        self.pushButtonForeward.setObjectName("pushButtonForeward")
        self.verticalLayout.addWidget(self.pushButtonForeward)
        self.spinBoxForeward = QtWidgets.QSpinBox(self.widget1)
        self.spinBoxForeward.setMaximum(10000)
        self.spinBoxForeward.setProperty("value", 90)
        self.spinBoxForeward.setObjectName("spinBoxForeward")
        self.verticalLayout.addWidget(self.spinBoxForeward)
        self.horizontalLayout.addLayout(self.verticalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pushButtonResetMotor = QtWidgets.QPushButton(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonResetMotor.sizePolicy().hasHeightForWidth())
        self.pushButtonResetMotor.setSizePolicy(sizePolicy)
        self.pushButtonResetMotor.setObjectName("pushButtonResetMotor")
        self.horizontalLayout.addWidget(self.pushButtonResetMotor)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButtonRollback = QtWidgets.QPushButton(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonRollback.sizePolicy().hasHeightForWidth())
        self.pushButtonRollback.setSizePolicy(sizePolicy)
        self.pushButtonRollback.setObjectName("pushButtonRollback")
        self.verticalLayout_2.addWidget(self.pushButtonRollback)
        self.spinBoxBack = QtWidgets.QSpinBox(self.widget1)
        self.spinBoxBack.setMaximum(10000)
        self.spinBoxBack.setProperty("value", 90)
        self.spinBoxBack.setObjectName("spinBoxBack")
        self.verticalLayout_2.addWidget(self.spinBoxBack)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 961, 27))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "StepDemo"))
        self.label_serial_state.setText(_translate("MainWindow", "串口状态：未连接"))
        self.pushButtonClose.setText(_translate("MainWindow", "关闭程序"))
        self.label_slider.setText(_translate("MainWindow", "正转角度:0"))
        self.pushButtonForeward.setText(_translate("MainWindow", "电机正转"))
        self.pushButtonResetMotor.setText(_translate("MainWindow", "电机回零点"))
        self.pushButtonRollback.setText(_translate("MainWindow", "电机反转"))

